#ifndef PEXCRAFT_MCPE_PROTOCOL_81_H
#define PEXCRAFT_MCPE_PROTOCOL_81_H

#define PEX_MCPE_PROTOCOL_81_FOLDER_NAME "protocol_81"
#define PEX_MCPE_PROTOCOL_81_DEFAULT_PROTOCOL 82
#define PEX_MCPE_PROTOCOL_81_MIN_PROTOCOL 81
#define PEX_MCPE_PROTOCOL_81_MAX_PROTOCOL 82

#endif /* PEXCRAFT_MCPE_PROTOCOL_81_H */
