execute_process(
  COMMAND ares-package "${CPACK_TEMPORARY_DIRECTORY}"
  WORKING_DIRECTORY "${CPACK_TEMPORARY_DIRECTORY}/.."
  RESULT_VARIABLE ARES_PACKAGE_RESULT
)
if(NOT ARES_PACKAGE_RESULT EQUAL 0)
  message(FATAL_ERROR "ares-package failed")
endif()
