#ifndef PEXCRAFT_MCPE_PROTOCOL_81_PACKET_IDS_H
#define PEXCRAFT_MCPE_PROTOCOL_81_PACKET_IDS_H

/* Genisys / PocketMine MCPE 0.15.4 packet IDs.
 * Folder stays protocol_81, but Genisys CURRENT_PROTOCOL is 82 and accepts 81/82.
 */
typedef enum PexMcpePacketId {
    PEX_MCPE_PACKET_LOGIN = 0x01,
    PEX_MCPE_PACKET_PLAY_STATUS = 0x02,
    PEX_MCPE_PACKET_SERVER_TO_CLIENT_HANDSHAKE = 0x03,
    PEX_MCPE_PACKET_CLIENT_TO_SERVER_HANDSHAKE = 0x04,
    PEX_MCPE_PACKET_DISCONNECT = 0x05,
    PEX_MCPE_PACKET_BATCH = 0x06,
    PEX_MCPE_PACKET_TEXT = 0x07,
    PEX_MCPE_PACKET_SET_TIME = 0x08,
    PEX_MCPE_PACKET_START_GAME = 0x09,
    PEX_MCPE_PACKET_ADD_PLAYER = 0x0a,
    PEX_MCPE_PACKET_REMOVE_ENTITY = 0x0c,
    PEX_MCPE_PACKET_ADD_ITEM_ENTITY = 0x0d,
    PEX_MCPE_PACKET_MOVE_ENTITY = 0x0f,
    PEX_MCPE_PACKET_MOVE_PLAYER = 0x10,
    PEX_MCPE_PACKET_REMOVE_BLOCK = 0x12,
    PEX_MCPE_PACKET_UPDATE_BLOCK = 0x13,
    PEX_MCPE_PACKET_MOB_EQUIPMENT = 0x1b,
    PEX_MCPE_PACKET_USE_ITEM = 0x1f,
    PEX_MCPE_PACKET_PLAYER_ACTION = 0x20,
    PEX_MCPE_PACKET_SET_ENTITY_DATA = 0x22,
    PEX_MCPE_PACKET_ANIMATE = 0x27,
    PEX_MCPE_PACKET_SET_HEALTH = 0x25,
    PEX_MCPE_PACKET_SET_SPAWN_POSITION = 0x26,
    PEX_MCPE_PACKET_CONTAINER_SET_SLOT = 0x2c,
    PEX_MCPE_PACKET_CONTAINER_SET_CONTENT = 0x2e,
    PEX_MCPE_PACKET_FULL_CHUNK_DATA = 0x34,
    PEX_MCPE_PACKET_SET_DIFFICULTY = 0x35,
    PEX_MCPE_PACKET_REQUEST_CHUNK_RADIUS = 0x3d,
    PEX_MCPE_PACKET_PLAYER_LIST = 0x38,
    PEX_MCPE_PACKET_CHUNK_RADIUS_UPDATED = 0x3e
} PexMcpePacketId;

#define PEX_MCPE_RAKLIB_GAME_PACKET 0xfe

#endif /* PEXCRAFT_MCPE_PROTOCOL_81_PACKET_IDS_H */
