/* GitHub Actions overwrites this file with a generated byte array made from
   Mojang's classic client.jar. Keeping a tiny stub lets local PSP builds still
   compile without network access. */
const unsigned char pexcraft_psp_classic_pack_zip[] = { 0 };
const unsigned int pexcraft_psp_classic_pack_zip_len = 0;
