#!/usr/bin/env python3
"""Bundle Minecraft-style lang files into a C include.

Inputs, in priority order:
  1. assets/lang/languages.txt plus assets/lang/*.lang
  2. src/assets/lang/languages.txt plus src/assets/lang/*.lang
  3. a jar/zip passed in PEXCRAFT_MINECRAFT_JAR or found at assets/client.jar / assets/Release/client.jar
  4. the checked-in fallback bundled_langs.inc

This script intentionally does not ship Mojang language files. If the exact
Minecraft 1.2.5 /lang directory is present in the repo or jar, it embeds those
exact files into src/i18n/bundled_langs.inc before the compiler runs.
"""
from __future__ import annotations
import os, re, sys, zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'src' / 'i18n' / 'bundled_langs.inc'
LANG_DIRS = [ROOT / 'assets' / 'lang', ROOT / 'src' / 'assets' / 'lang']
JARS = []
if os.environ.get('PEXCRAFT_MINECRAFT_JAR'):
    JARS.append(Path(os.environ['PEXCRAFT_MINECRAFT_JAR']))
JARS += [ROOT / 'assets' / 'client.jar', ROOT / 'assets' / 'Release' / 'client.jar']

def cstr(s: str) -> str:
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '') + '"'

def sanitize(code: str) -> str:
    return re.sub(r'[^A-Za-z0-9_]', '_', code)

def parse_languages_txt(text: str) -> list[tuple[str, str]]:
    out = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith('#') or '=' not in line: continue
        k, v = line.split('=', 1)
        k = k.strip(); v = v.strip()
        if k: out.append((k, v or k))
    return out

def parse_lang(text: str) -> list[tuple[str, str]]:
    out = []
    for raw in text.splitlines():
        line = raw.strip('\ufeff').strip()
        if not line or line.startswith('#') or '=' not in line: continue
        k, v = line.split('=', 1)  # matches old StringTranslate behavior closely enough for clean .lang files
        k = k.strip(); v = v.strip()
        if k: out.append((k, v))
    return out

def load_from_dir(d: Path):
    languages = d / 'languages.txt'
    if not languages.exists(): return None
    lang_list = parse_languages_txt(languages.read_text(encoding='utf-8', errors='replace'))
    result = []
    for code, name in lang_list:
        f = d / f'{code}.lang'
        if f.exists():
            result.append((code, name, parse_lang(f.read_text(encoding='utf-8', errors='replace'))))
    return result if result else None

def load_from_jar(jar: Path):
    if not jar.exists(): return None
    with zipfile.ZipFile(jar, 'r') as z:
        try:
            languages_txt = z.read('lang/languages.txt').decode('utf-8', errors='replace')
        except KeyError:
            return None
        lang_list = parse_languages_txt(languages_txt)
        result = []
        for code, name in lang_list:
            try:
                txt = z.read(f'lang/{code}.lang').decode('utf-8', errors='replace')
            except KeyError:
                continue
            result.append((code, name, parse_lang(txt)))
        return result if result else None

def find_langs():
    for d in LANG_DIRS:
        r = load_from_dir(d)
        if r: return r, f'directory {d}'
    for j in JARS:
        r = load_from_jar(j)
        if r: return r, f'jar {j}'
    return None, None

def main() -> int:
    langs, source = find_langs()
    if not langs:
        print('bundle_langs.py: no Minecraft /lang source found; keeping fallback bundled_langs.inc')
        return 0
    lines = []
    lines.append('/* Auto-generated by tools/bundle_langs.py from %s. */' % source.replace('*/', '* /'))
    for code, name, entries in langs:
        sym = sanitize(code)
        lines.append(f'static const PexLangEntry pex_lang_{sym}[] = {{')
        for k, v in entries:
            lines.append(f'    {{{cstr(k)}, {cstr(v)}}},')
        lines.append('};')
    lines.append('static const PexBundledLanguage pex_bundled_langs[] = {')
    for code, name, entries in langs:
        sym = sanitize(code)
        lines.append(f'    {{{cstr(code)}, {cstr(name)}, pex_lang_{sym}, (int)(sizeof(pex_lang_{sym}) / sizeof(pex_lang_{sym}[0]))}},')
    lines.append('};')
    lines.append('#define PEX_BUNDLED_LANG_COUNT ((int)(sizeof(pex_bundled_langs) / sizeof(pex_bundled_langs[0])))')
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'bundle_langs.py: embedded {len(langs)} language files from {source} -> {OUT}')
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
