#!/usr/bin/env python3
"""Generate a forced-include C header containing Git build metadata.

Values are resolved in this order:
  1. PEX_BUILD_* environment overrides.
  2. GitHub Actions environment variables.
  3. The current local Git checkout.
  4. Empty strings when no Git metadata is available.

The output is only rewritten when its contents change, avoiding unnecessary
full unity-build recompiles.
"""

import argparse
import os
from pathlib import Path
import re
import subprocess
import sys
from urllib.parse import urlsplit, urlunsplit


def run_git(root, *args):
    try:
        proc = subprocess.run(
            ["git", "-c", "safe.directory=*", "-C", str(root), *args],
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            universal_newlines=True,
            encoding="utf-8",
            errors="replace",
        )
    except OSError:
        return ""
    return proc.stdout.strip() if proc.returncode == 0 else ""


def first_nonempty(*values):
    for value in values:
        if value:
            value = value.strip()
            if value:
                return value
    return ""


def one_line(value, limit):
    value = value.replace("\r", " ").replace("\n", " ").replace("\t", " ")
    value = " ".join(value.split())
    return value[:limit]


def normalize_sha(value):
    value = value.strip().lower()
    return value if re.fullmatch(r"[0-9a-f]{7,64}", value) else ""


def normalize_repo_url(value):
    value = value.strip()
    if not value:
        return ""

    # Common Git SSH forms.
    match = re.fullmatch(r"git@([^:]+):(.+)", value)
    if match:
        value = f"https://{match.group(1)}/{match.group(2)}"
    elif value.startswith("ssh://git@"):
        value = "https://" + value[len("ssh://git@") :]
    elif value.startswith("git://"):
        value = "https://" + value[len("git://") :]

    if value.endswith(".git"):
        value = value[:-4]
    value = value.rstrip("/")

    try:
        parts = urlsplit(value)
    except ValueError:
        return ""
    if parts.scheme not in {"http", "https"} or not parts.netloc or not parts.path.strip("/"):
        return ""

    # Drop credentials, query strings, and fragments from a remote URL before
    # embedding it into the executable.
    host = parts.hostname or ""
    if not host:
        return ""
    if parts.port:
        host = f"{host}:{parts.port}"
    path = "/" + parts.path.strip("/")
    return urlunsplit(("https", host, path, "", ""))


def c_string(value):
    out = []
    for ch in value:
        code = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif 0x20 <= code <= 0x7E:
            out.append(ch)
        else:
            # Commit subjects are UTF-8 in Git, but source/toolchains include
            # several old console compilers. Preserve non-ASCII as UTF-8 byte
            # escapes so every generated header remains plain ASCII.
            for byte in ch.encode("utf-8"):
                out.append(f"\\{byte:03o}")
    return "".join(out)


def resolve(root):
    env = os.environ

    commit_hash = normalize_sha(
        first_nonempty(
            env.get("PEX_BUILD_COMMIT_HASH"),
            run_git(root, "rev-parse", "HEAD"),
            env.get("GITHUB_SHA"),
        )
    )

    commit_name = one_line(
        first_nonempty(
            env.get("PEX_BUILD_COMMIT_NAME"),
            env.get("COMMIT_NAME"),
            run_git(root, "log", "-1", "--pretty=%s"),
        ),
        240,
    )

    github_repository = first_nonempty(env.get("GITHUB_REPOSITORY"))
    github_server = first_nonempty(env.get("GITHUB_SERVER_URL"), "https://github.com")
    actions_repo_url = f"{github_server.rstrip('/')}/{github_repository}" if github_repository else ""
    repository_url = normalize_repo_url(
        first_nonempty(
            env.get("PEX_BUILD_REPOSITORY_URL"),
            actions_repo_url,
            run_git(root, "remote", "get-url", "origin"),
        )
    )

    commit_url = ""
    if repository_url and commit_hash:
        commit_url = f"{repository_url}/commit/{commit_hash}"

    return commit_name, commit_hash, repository_url, commit_url


def render(commit_name, commit_hash, repository_url, commit_url):
    return f"""/* Auto-generated by tools/generate_build_info.py. Do not edit. */
#ifndef PEX_BUILD_INFO_GENERATED_H
#define PEX_BUILD_INFO_GENERATED_H
#define PEX_BUILD_COMMIT_NAME \"{c_string(commit_name)}\"
#define PEX_BUILD_COMMIT_HASH \"{c_string(commit_hash)}\"
#define PEX_BUILD_REPOSITORY_URL \"{c_string(repository_url)}\"
#define PEX_BUILD_COMMIT_URL \"{c_string(commit_url)}\"
#endif
"""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="repository root (default: parent of tools/)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="output header (default: <root>/build/generated/pex_build_info.h)",
    )
    parser.add_argument("--print", action="store_true", dest="print_values")
    args = parser.parse_args()

    root = args.root.resolve()
    output = args.output or root / "build" / "generated" / "pex_build_info.h"
    if not output.is_absolute():
        output = root / output

    values = resolve(root)
    content = render(*values)
    output.parent.mkdir(parents=True, exist_ok=True)

    old = ""
    try:
        old = output.read_text(encoding="ascii")
    except (OSError, UnicodeError):
        pass
    if old != content:
        temp = output.with_name(f".{output.name}.{os.getpid()}.tmp")
        with temp.open("w", encoding="ascii", newline="\n") as handle:
            handle.write(content)
        os.replace(str(temp), str(output))

    if args.print_values:
        labels = ("name", "hash", "repository", "url")
        for label, value in zip(labels, values):
            print(f"{label}={value}")
    else:
        shown_hash = values[1] or "(empty)"
        shown_name = values[0] or "(empty)"
        print(f"Build info: {shown_hash} {shown_name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
