#!/usr/bin/env python3
"""Prepare Nintendo Wii embedded texture assets for PexCraft.

The Wii build must not depend on external texture files on SD.  This script
mirrors the PSP asset flow: download Minecraft Classic client.jar during CI,
convert the textures needed by the game into compact MCRW files, pack those
MCRW files into one binary pak, and generate an assembly wrapper that links
that pak directly into boot.dol.
"""
import io
import shutil
import struct
import sys
import urllib.request
import zipfile
from pathlib import Path

CLASSIC_PACK_URL = "https://piston-data.mojang.com/v1/objects/93faf3398ebf8008d59852dc3c2b22b909ca8a49/client.jar"

REQUIRED_MCRW = {
    "gui_background.mcrw", "gui_gui.mcrw", "font_default.mcrw", "terrain.mcrw",
    "title_black.mcrw", "gui_icons.mcrw", "gui_inventory.mcrw", "mob_char.mcrw",
}

MAPPING = {
    "terrain.png": "terrain.mcrw",
    "gui/gui.png": "gui_gui.mcrw",
    "gui/background.png": "gui_background.mcrw",
    "gui/icons.png": "gui_icons.mcrw",
    "gui/inventory.png": "gui_inventory.mcrw",
    "gui/items.png": "gui_items.mcrw",
    "font/default.png": "font_default.mcrw",
    "mob/char.png": "mob_char.mcrw",
    "gui/crafting.png": "gui_crafting_table.mcrw",
    "gui/furnace.png": "gui_furnace.mcrw",
    "gui/container.png": "gui_chest.mcrw",
    "title/black.png": "title_black.mcrw",
    "environment/clouds.png": "environment_clouds.mcrw",
    "misc/water.png": "misc_water.mcrw",
    "misc/shadow.png": "misc_shadow.mcrw",
    "misc/grasscolor.png": "misc_grasscolor.mcrw",
    "misc/foliagecolor.png": "misc_foliagecolor.mcrw",
    "particles.png": "particles.mcrw",
}


def require_pillow():
    try:
        from PIL import Image
        return Image
    except Exception as exc:
        raise SystemExit(f"Pillow is required for PNG -> MCRW conversion: {exc}")


def write_mcrw(path: Path, im):
    path.parent.mkdir(parents=True, exist_ok=True)
    rgba = im.tobytes()
    with path.open("wb") as f:
        f.write(b"MCRW")
        f.write(struct.pack("<II", im.width, im.height))
        f.write(rgba)
    print(f"mcrw {path} {im.width}x{im.height}")


def copy_existing_mcrw(out_assets: Path):
    src_assets = Path("assets")
    out_assets.mkdir(parents=True, exist_ok=True)
    if not src_assets.exists():
        return
    for p in src_assets.iterdir():
        if p.is_file() and p.suffix.lower() == ".mcrw":
            shutil.copyfile(p, out_assets / p.name)


def download_client_jar(jar: Path):
    jar.parent.mkdir(parents=True, exist_ok=True)
    if jar.exists() and jar.stat().st_size > 0:
        print(f"using cached client.jar: {jar}")
        return True
    print("downloading client.jar for Wii embedded textures")
    try:
        urllib.request.urlretrieve(CLASSIC_PACK_URL, jar)
        return jar.exists() and jar.stat().st_size > 0
    except Exception as exc:
        print(f"WARNING: could not download client.jar; using existing fallback MCRW assets only: {exc}", file=sys.stderr)
        return False


def convert_client_jar(jar: Path, out_assets: Path, Image):
    if not jar.exists() or jar.stat().st_size <= 0:
        return
    with zipfile.ZipFile(jar, "r") as zf:
        names = set(zf.namelist())
        for src, dst in MAPPING.items():
            if src not in names:
                print(f"missing in client.jar: {src}")
                continue
            with zf.open(src) as f:
                im = Image.open(io.BytesIO(f.read())).convert("RGBA")
            write_mcrw(out_assets / dst, im)


def write_mcrw_pak_and_asm(out_assets: Path, pak_path: Path, asm_path: Path):
    files = sorted([p for p in out_assets.iterdir() if p.is_file() and p.suffix.lower() == ".mcrw"])
    pak_path.parent.mkdir(parents=True, exist_ok=True)
    asm_path.parent.mkdir(parents=True, exist_ok=True)

    magic = b"PXCMCRW1"
    header_size = 8 + 4
    for path in files:
        header_size += 12 + len(path.name.encode("utf-8"))
    data_offset = (header_size + 3) & ~3

    entries = []
    blobs = []
    cur = data_offset
    for path in files:
        data = path.read_bytes()
        name_b = path.name.encode("utf-8")
        entries.append((name_b, len(data), cur))
        blobs.append(data)
        cur += len(data)
        cur = (cur + 3) & ~3

    with pak_path.open("wb") as f:
        f.write(magic)
        f.write(struct.pack("<I", len(entries)))
        for name_b, data_len, off in entries:
            f.write(struct.pack("<III", len(name_b), data_len, off))
            f.write(name_b)
        pad = data_offset - f.tell()
        if pad > 0:
            f.write(b"\0" * pad)
        for data in blobs:
            f.write(data)
            pad = ((f.tell() + 3) & ~3) - f.tell()
            if pad > 0:
                f.write(b"\0" * pad)

    asm_path.write_text(
        "/* generated by tools/prepare_wii_assets.py; do not commit build/ */\n"
        "    .section .wii_assets,\"a\"\n"
        "    .align 4\n"
        "    .global pexcraft_wii_mcrw_assets_pak_start\n"
        "pexcraft_wii_mcrw_assets_pak_start:\n"
        f"    .incbin \"{pak_path.as_posix()}\"\n"
        "    .align 4\n"
        "    .global pexcraft_wii_mcrw_assets_pak_end\n"
        "pexcraft_wii_mcrw_assets_pak_end:\n",
        encoding="utf-8",
    )
    print(f"packed Wii MCRW assets: {len(files)} files -> {pak_path} ({pak_path.stat().st_size} bytes)")
    print(f"embedded Wii pak asm wrapper -> {asm_path}")


def main():
    out_assets = Path(sys.argv[1] if len(sys.argv) > 1 else "build/wii_generated/assets")
    pak_path = Path(sys.argv[2] if len(sys.argv) > 2 else "build/wii_generated/wii_mcrw_assets.pak")
    asm_path = Path(sys.argv[3] if len(sys.argv) > 3 else "build/wii_generated/wii_mcrw_assets.S")
    work = Path("build/wii_classic_work")
    jar = work / "client.jar"

    Image = require_pillow()
    if out_assets.exists():
        shutil.rmtree(out_assets)
    out_assets.mkdir(parents=True, exist_ok=True)

    copy_existing_mcrw(out_assets)
    if download_client_jar(jar):
        convert_client_jar(jar, out_assets, Image)

    have = {p.name for p in out_assets.glob("*.mcrw")}
    missing = sorted(REQUIRED_MCRW - have)
    if missing:
        print("WARNING: missing required MCRW assets before embedding: " + ", ".join(missing), file=sys.stderr)

    write_mcrw_pak_and_asm(out_assets, pak_path, asm_path)


if __name__ == "__main__":
    main()
