#!/usr/bin/env python3
import io, os, struct, sys, zipfile, urllib.request
from pathlib import Path

CLASSIC_PACK_URL = "https://piston-data.mojang.com/v1/objects/93faf3398ebf8008d59852dc3c2b22b909ca8a49/client.jar"

REQUIRED_MCRW = {
    "gui_background.mcrw", "gui_gui.mcrw", "font_default.mcrw", "terrain.mcrw",
    "title_black.mcrw", "gui_icons.mcrw", "achievement_bg.mcrw", "gui_slot.mcrw", "gui_inventory.mcrw", "mob_char.mcrw",
}

def require_pillow():
    try:
        from PIL import Image
        return Image
    except Exception as e:
        print("Pillow is required for PNG -> MCRW conversion", e, file=sys.stderr)
        raise

def read_png_rgba(zf, name, Image):
    with zf.open(name) as f:
        im = Image.open(io.BytesIO(f.read())).convert('RGBA')
    return im

def write_mcrw(path, im):
    path.parent.mkdir(parents=True, exist_ok=True)
    rgba = im.tobytes()
    with open(path, 'wb') as f:
        f.write(b'MCRW')
        f.write(struct.pack('<II', im.width, im.height))
        f.write(rgba)
    print(f"mcrw {path} {im.width}x{im.height}")

def write_mcrw_pak_and_asm(out_assets, pak_path, asm_path):
    """Write all generated .mcrw files into one compact binary pak and an
    assembly wrapper that embeds the pak with .incbin.

    This avoids committing a massive C file full of 0xNN byte literals.
    The repo stays small; GitHub Actions generates the pak/asm just before
    the PSP build and links it into EBOOT.PBP.
    """
    files = sorted([p for p in out_assets.iterdir() if p.is_file() and p.suffix.lower() == '.mcrw'])
    pak_path.parent.mkdir(parents=True, exist_ok=True)
    asm_path.parent.mkdir(parents=True, exist_ok=True)

    # Pak format, little endian:
    #   8 bytes magic: b'PXCMCRW1'
    #   u32 count
    #   repeated count times:
    #       u32 name_len
    #       u32 data_len
    #       u32 data_offset_from_pak_start
    #       name bytes, UTF-8, no NUL
    #   data blobs, 4-byte aligned
    magic = b'PXCMCRW1'
    entries_meta = []
    header_size = 8 + 4
    for path in files:
        name_b = path.name.encode('utf-8')
        header_size += 12 + len(name_b)
    data_offset = (header_size + 3) & ~3
    data_blobs = []
    cur = data_offset
    for path in files:
        data = path.read_bytes()
        name_b = path.name.encode('utf-8')
        entries_meta.append((name_b, len(data), cur))
        data_blobs.append(data)
        cur += len(data)
        cur = (cur + 3) & ~3

    with open(pak_path, 'wb') as f:
        f.write(magic)
        f.write(struct.pack('<I', len(entries_meta)))
        for name_b, data_len, off in entries_meta:
            f.write(struct.pack('<III', len(name_b), data_len, off))
            f.write(name_b)
        pad = data_offset - f.tell()
        if pad > 0:
            f.write(b'\0' * pad)
        for data in data_blobs:
            f.write(data)
            pad = ((f.tell() + 3) & ~3) - f.tell()
            if pad > 0:
                f.write(b'\0' * pad)

    # Use an assembly .incbin wrapper. This compiles into a tiny object and
    # keeps the binary bytes binary instead of expanding them into a huge .c.
    incbin_path = pak_path.as_posix()
    asm_path.write_text(
        '/* generated by tools/prepare_psp_assets.py; do not commit build/ */\n'
        '    .section .rodata\n'
        '    .align 4\n'
        '    .global pexcraft_psp_mcrw_assets_pak_start\n'
        'pexcraft_psp_mcrw_assets_pak_start:\n'
        f'    .incbin "{incbin_path}"\n'
        '    .align 4\n'
        '    .global pexcraft_psp_mcrw_assets_pak_end\n'
        'pexcraft_psp_mcrw_assets_pak_end:\n',
        encoding='utf-8'
    )
    print(f'packed PSP MCRW assets: {len(files)} files -> {pak_path} ({pak_path.stat().st_size} bytes)')
    print(f'embedded pak asm wrapper -> {asm_path}')


def main():
    out_assets = Path(sys.argv[1] if len(sys.argv) > 1 else 'build/psp_generated/assets')
    embed_c = Path(sys.argv[2] if len(sys.argv) > 2 else 'src/assets/psp_embedded_classic_pack.c')
    pak_path = Path(sys.argv[3] if len(sys.argv) > 3 else 'build/psp_generated/psp_mcrw_assets.pak')
    asm_path = Path(sys.argv[4] if len(sys.argv) > 4 else 'build/psp_generated/psp_mcrw_assets.S')
    work = Path('build/psp_classic_work')
    jar = work / 'client.jar'
    work.mkdir(parents=True, exist_ok=True)
    if not jar.exists():
        print('downloading client.jar')
        try:
            urllib.request.urlretrieve(CLASSIC_PACK_URL, jar)
        except Exception as e:
            print('WARNING: could not download client.jar; embedding existing assets only:', e, file=sys.stderr)
    Image = require_pillow()
    mapping = {
        'terrain.png': 'terrain.mcrw',
        'gui/gui.png': 'gui_gui.mcrw',
        'gui/background.png': 'gui_background.mcrw',
        'gui/icons.png': 'gui_icons.mcrw',
        'achievement/bg.png': 'achievement_bg.mcrw',
        'gui/slot.png': 'gui_slot.mcrw',
        'gui/inventory.png': 'gui_inventory.mcrw',
        'gui/items.png': 'gui_items.mcrw',
        'font/default.png': 'font_default.mcrw',
        'mob/char.png': 'mob_char.mcrw',
        'gui/crafting.png': 'gui_crafting_table.mcrw',
        'gui/furnace.png': 'gui_furnace.mcrw',
        'gui/container.png': 'gui_chest.mcrw',
        'title/black.png': 'title_black.mcrw',
        'environment/clouds.png': 'environment_clouds.mcrw',
        'misc/water.png': 'misc_water.mcrw',
        'misc/shadow.png': 'misc_shadow.mcrw',
        'misc/grasscolor.png': 'misc_grasscolor.mcrw',
        'misc/foliagecolor.png': 'misc_foliagecolor.mcrw',
        'particles.png': 'particles.mcrw',
    }
    # Start with existing fallback assets, then overwrite with Java's assets.
    src_assets = Path('assets')
    out_assets.mkdir(parents=True, exist_ok=True)
    if src_assets.exists():
        for p in src_assets.iterdir():
            if p.is_file() and p.suffix.lower() == '.mcrw':
                (out_assets / p.name).write_bytes(p.read_bytes())
    classic = work / 'Minecraft Classic'
    if classic.exists():
        import shutil; shutil.rmtree(classic)
    classic.mkdir(parents=True)
    if jar.exists():
        with zipfile.ZipFile(jar, 'r') as zf:
            names = set(zf.namelist())
            for src, dst in mapping.items():
                if src not in names:
                    print('missing in jar:', src)
                    continue
                im = read_png_rgba(zf, src, Image)
                write_mcrw(out_assets / dst, im)
            # Make an embedded texture-pack zip with the original Java PNG layout.
            for name in zf.namelist():
                if name.endswith('/') or name.startswith('META-INF/') or name.endswith('.class'):
                    continue
                if name == 'pack.png':
                    continue
                if name == 'terrain.png' or name == 'particles.png' or name.startswith(('gui/','font/','mob/','title/','environment/','misc/')):
                    dest = classic / name
                    dest.parent.mkdir(parents=True, exist_ok=True)
                    dest.write_bytes(zf.read(name))
    else:
        print('WARNING: client.jar unavailable; embedded Classic pack zip will contain only pack.txt', file=sys.stderr)
    (classic / 'pack.txt').write_text('Minecraft Classic\nEmbedded from client.jar for PSP\n', encoding='utf-8')
    embedded_zip = work / 'psp_embedded_classic_pack.zip'
    with zipfile.ZipFile(embedded_zip, 'w', zipfile.ZIP_DEFLATED) as out:
        for p in classic.rglob('*'):
            if p.is_file():
                out.write(p, p.relative_to(classic).as_posix())
    data = embedded_zip.read_bytes()
    embed_c.parent.mkdir(parents=True, exist_ok=True)
    with open(embed_c, 'w', encoding='utf-8') as f:
        f.write('/* generated by tools/prepare_psp_assets.py */\n')
        f.write('#include <stddef.h>\n')
        f.write('const unsigned char pexcraft_psp_classic_pack_zip[] = {\n')
        for i in range(0, len(data), 12):
            f.write('  ' + ', '.join(f'0x{b:02x}' for b in data[i:i+12]) + ',\n')
        f.write('};\n')
        f.write(f'const unsigned int pexcraft_psp_classic_pack_zip_len = {len(data)}u;\n')
    print(f'embedded classic pack: {len(data)} bytes -> {embed_c}')
    have = {p.name for p in out_assets.glob('*.mcrw')}
    missing = sorted(REQUIRED_MCRW - have)
    if missing:
        print('WARNING: missing required MCRW assets before embedding:', ', '.join(missing), file=sys.stderr)
    write_mcrw_pak_and_asm(out_assets, pak_path, asm_path)

if __name__ == '__main__':
    main()
