#!/usr/bin/env python3
import io, os, struct, sys, zipfile, urllib.request
from pathlib import Path

CLASSIC_PACK_URL = "https://piston-data.mojang.com/v1/objects/93faf3398ebf8008d59852dc3c2b22b909ca8a49/client.jar"

def require_pillow():
    try:
        from PIL import Image
        return Image
    except Exception as e:
        print("Pillow is required for PNG -> MCRW conversion", e, file=sys.stderr)
        raise

def read_png_rgba(zf, name, Image):
    with zf.open(name) as f:
        im = Image.open(io.BytesIO(f.read())).convert('RGBA')
    return im

def write_mcrw(path, im):
    path.parent.mkdir(parents=True, exist_ok=True)
    rgba = im.tobytes()
    with open(path, 'wb') as f:
        f.write(b'MCRW')
        f.write(struct.pack('<II', im.width, im.height))
        f.write(rgba)
    print(f"mcrw {path} {im.width}x{im.height}")

def main():
    out_assets = Path(sys.argv[1] if len(sys.argv) > 1 else 'build/psp_generated/assets')
    embed_c = Path(sys.argv[2] if len(sys.argv) > 2 else 'src/assets/psp_embedded_classic_pack.c')
    work = Path('build/psp_classic_work')
    jar = work / 'client.jar'
    work.mkdir(parents=True, exist_ok=True)
    if not jar.exists():
        print('downloading client.jar')
        urllib.request.urlretrieve(CLASSIC_PACK_URL, jar)
    Image = require_pillow()
    mapping = {
        'terrain.png': 'terrain.mcrw',
        'gui/gui.png': 'gui_gui.mcrw',
        'gui/background.png': 'gui_background.mcrw',
        'gui/icons.png': 'gui_icons.mcrw',
        'gui/inventory.png': 'gui_inventory.mcrw',
        'gui/items.png': 'gui_items.mcrw',
        'font/default.png': 'font_default.mcrw',
        'mob/char.png': 'mob_char.mcrw',
        'gui/crafting.png': 'gui_crafting_table.mcrw',
        'gui/furnace.png': 'gui_furnace.mcrw',
        'gui/container.png': 'gui_chest.mcrw',
        'title/black.png': 'title_black.mcrw',
    }
    # Start with existing fallback assets, then overwrite with Java's assets.
    src_assets = Path('assets')
    out_assets.mkdir(parents=True, exist_ok=True)
    if src_assets.exists():
        for p in src_assets.iterdir():
            if p.is_file() and p.suffix.lower() == '.mcrw':
                (out_assets / p.name).write_bytes(p.read_bytes())
    classic = work / 'Minecraft Classic'
    if classic.exists():
        import shutil; shutil.rmtree(classic)
    classic.mkdir(parents=True)
    with zipfile.ZipFile(jar, 'r') as zf:
        names = set(zf.namelist())
        for src, dst in mapping.items():
            if src not in names:
                print('missing in jar:', src)
                continue
            im = read_png_rgba(zf, src, Image)
            write_mcrw(out_assets / dst, im)
        # Make an embedded texture-pack zip with the original Java PNG layout.
        keep_prefixes = ('terrain.png','gui/','font/','mob/','title/')
        for name in zf.namelist():
            if name.endswith('/') or name.startswith('META-INF/') or name.endswith('.class'):
                continue
            if name == 'pack.png':
                continue
            if name == 'terrain.png' or name.startswith(('gui/','font/','mob/','title/')):
                dest = classic / name
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_bytes(zf.read(name))
    (classic / 'pack.txt').write_text('Minecraft Classic\nEmbedded from client.jar for PSP\n', encoding='utf-8')
    embedded_zip = work / 'psp_embedded_classic_pack.zip'
    with zipfile.ZipFile(embedded_zip, 'w', zipfile.ZIP_DEFLATED) as out:
        for p in classic.rglob('*'):
            if p.is_file():
                out.write(p, p.relative_to(classic).as_posix())
    data = embedded_zip.read_bytes()
    embed_c.parent.mkdir(parents=True, exist_ok=True)
    with open(embed_c, 'w', encoding='utf-8') as f:
        f.write('/* generated by tools/prepare_psp_assets.py */\n')
        f.write('#include <stddef.h>\n')
        f.write('const unsigned char pexcraft_psp_classic_pack_zip[] = {\n')
        for i in range(0, len(data), 12):
            f.write('  ' + ', '.join(f'0x{b:02x}' for b in data[i:i+12]) + ',\n')
        f.write('};\n')
        f.write(f'const unsigned int pexcraft_psp_classic_pack_zip_len = {len(data)}u;\n')
    print(f'embedded classic pack: {len(data)} bytes -> {embed_c}')

if __name__ == '__main__':
    main()
