/* PEXCRAFT b1.0 C port split-source unity entry. */
#include "common/common.h"

#include "platform/filesystem.c"
#include "assets/textures.c"
#include "save/nbt_gzip_save.c"
#include "worldgen/beta_generator.c"
#include "game/world_session.c"
#include "render/gui_primitives.c"
#include "settings/options.c"
#include "platform/input.c"
#include "game/flat_world_inventory.c"
#include "ui/screen_state_input.c"
#include "ui/title_menus.c"
#include "game/ingame_logic.c"
#include "render/world_view.c"
#include "render/item_render.c"
#include "ui/hud_pause_inventory_chat.c"
#include "render/render_dispatch.c"
#include "platform/win32_app.c"
